sudo: required

services:
    - docker

before install:
    - docker build -f ./dockerfile -t cbsaikumar/fullstack-with-docker .

script:
    - docker run cbsaikumar/fullstack-with-docker

deploy:
    provider: elasticbeanstalk
    access_key_id: $access_key_id
    secret_access_key: 
        secure: $secret_access_key
    region: "us-east-1"
    app: "fullstack-with-docker"
    env: "fullstack-with-docker-env"
    bucket_name: "fullstack-with-docker-s3-bucket-8080"
    on:
        branch: master
